export const lookupAttribute = {
    Country: { id: 'country', name: 'country', label: 'Country', lookupName: 'Countries' , labelId : ''},
    State: { id: 'state', name: 'state', label: 'State', lookupName: 'States' , labelId : ''},
    City: { id: 'city', name: 'city', label: 'City', lookupName: 'Cities' , labelId : ''},
    Gender: { id: 'gender', name: 'gender', label: 'Gender', lookupName: 'Genders',outputName :'genders' , labelId : ''},
    Category: { id: 'category', name: 'category', label: 'Category', lookupName: 'Categories',outputName :'categories' , labelId : ''},
    Religion: { id: 'religion', name: 'religion', label: 'Religion', lookupName: 'Religions',outputName :'religions' , labelId : ''},
    Designation: { id: 'designation', name: 'designation', label: 'Designation', lookupName: 'Designations',outputName :'designations' , labelId : ''},
    Department: { id: 'department', name: 'department', label: 'Department', lookupName: 'Departments',outputName :'departments' , labelId : ''},
    BloodGroup: { id: 'bloodGroup', name: 'bloodGroup', label: 'Blood Group', lookupName: 'BloodGroups',outputName :'bloodGroups' , labelId : ''},
    EmployeeType: { id: 'employeeType', name: 'employeeType', label: 'Employee Type', lookupName: 'EmployeeTypes',outputName :'employeeTypes' , labelId : ''},
    ProductType: { id: 'productType', name: 'productType', label: 'Product Type', lookupName: 'ProductTypes',outputName :'productTypes' , labelId : ''},
    StudentType: { id: 'studentType', name: 'studentType', label: 'Student Type', lookupName: 'StudentTypes',outputName :'studentTypes' , labelId : ''},
    Product: { id: 'product', name: 'product', label: 'Product Name', lookupName: 'Products',outputName :'products' , labelId : ''},
    ProdCategory: { id: 'productCategory', name: 'productCategory', label: 'Prod Category', lookupName: 'ProdCategories',outputName :'prodCategories' , labelId : ''},
    ProdSubCategory: { id: 'prodSubCategory', name: 'prodSubCategory', label: 'Sub Category', lookupName: 'ProdSubCategories' , labelId : ''},
    Unit: { id: 'unit', name: 'unit', label: 'Unit', lookupName: 'Units',outputName :'units' , labelId : ''},
    UnitInItem: { id: 'unitInItem', name: 'unitInItem', label: 'Unit' , lookupName: 'Units',outputName :'units' , labelId : 'lblUnitInItem'}, 
    Section: { id: 'section', name: 'section', label: 'Section', lookupName: 'Sections' , outputName :'sections', labelId : ''},
    Class: { id: 'class', name: 'class', label: 'Class', lookupName: 'Classes',outputName :'classes' , labelId : ''},
    PrevClass: { id: 'prevclass', name: 'prevclass', label: 'Prev Class', lookupName: 'Classes', outputName :'classes'},
    Session: { id: 'session', name: 'session', label: 'Session', lookupName: 'Sessions',outputName :'sessions' , labelId : ''}, 
    Branch: { id: 'branch', name: 'branch', label: 'Branch', lookupName: 'Branches', outputName :'branches', labelId : ''},  
    FatherQualification: { id: 'fatherQualification', name: 'fatherQualification', label: 'Father Qualification', lookupName: 'Qualifications', outputName :'qualifications', labelId : ''},
    HighestQualification: { id: 'highestQualification', name: 'highestQualification', label: 'Highest Qualification', lookupName: 'Qualifications', outputName :'qualifications', labelId : ''},
    FromMonths: { id: 'fromMonths', name: 'fromMonths', label: 'From Months', lookupName: 'Months', outputName :'months', labelId : ''},
    ToMonths: { id: 'toMonths', name: 'toMonths', label: 'To Months', lookupName: 'Months', outputName :'months', labelId : ''},
    InstallmentType: { id: 'installmentType', name: 'installmentType', label: 'Installment Type', lookupName: 'InstallmentType', outputName :'installmentTypes', labelId : ''},
    InstallmentPlan: { id: 'installmentPlan', name: 'installmentPlan', label: 'Installment Plan', lookupName: 'InstallmentPlan', outputName :'installmentPlans', labelId : ''},
    FeeComponent: { id: 'feeComponent', name: 'feeComponent', label: 'Fee Component', lookupName: 'FeeComponent', outputName :'feeComponents', labelId : ''},
    FeeInstallment: { id: 'feeInstallment', name: 'feeInstallment', label: 'Fee Installment', lookupName: 'FeeInstallment', outputName :'feeInstallments', labelId : ''},
    PaymentType: { id: 'paymentType', name: 'paymentType', label: 'Payment Type', lookupName: 'PaymentType', outputName :'paymentTypes', labelId : ''},
    Employee: { id: 'employee', name: 'employee', label: 'Employee', lookupName: 'Employee', outputName :'employees', labelId : ''},  
    UserType: { id: 'userType', name: 'employee', label: 'User Type', lookupName: 'UserType', outputName :'userTypes', labelId : ''},      
};